#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: ${MYSQL_CLUSTER_NS}-${MYSQL_CLUSTER_NAME}-data
#provisioner: ebs.csi.aws.com
#allowVolumeExpansion: true
#---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${MYSQL_CLUSTER_NS}
  name: ${MYSQL_CLUSTER_NAME}-conf
data:
  long_query_time: "5"
#  innodb_buffer_pool_size: "10G"