#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: ${MYSQL_CLUSTER_NS}-${MYSQL_CLUSTER_NAME}-data
#provisioner: ebs.csi.aws.com
#allowVolumeExpansion: true
#---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ${MYSQL_CLUSTER_NS}
  name: ${MYSQL_CLUSTER_NAME}-conf
data:
  long_query_time: "5"
#  innodb_buffer_pool_size: "10G"
---
apiVersion: moco.cybozu.com/v1beta2
kind: BackupPolicy
metadata:
  namespace: ${MYSQL_CLUSTER_NS}
  name: ${MYSQL_CLUSTER_NAME}-daily-backup
spec:
  schedule: "@daily"

  jobConfig:
    serviceAccountName: ${MYSQL_CLUSTER_SERVICE_ACCOUNT}
    bucketConfig:
      bucketName: ${MYSQL_CLUSTER_S3_BUCKET}
#      prefix: /mysql/${MYSQL_CLUSTER_NAME}/dumps/
      usePathStyle: true

    workVolume:
      emptyDir: {}
---
apiVersion: moco.cybozu.com/v1beta2
kind: MySQLCluster
metadata:
  namespace: ${MYSQL_CLUSTER_NS}
  name: ${MYSQL_CLUSTER_NAME}
spec:
  mysqlConfigMapName: ${MYSQL_CLUSTER_NAME}-conf
  backupPolicyName: ${MYSQL_CLUSTER_NAME}-daily-backup
  replicas: 1
  podTemplate:
    spec:
      nodeSelector:
        intent: apps
        node.kubernetes.io/instance-type: c6a.xlarge
      # Make the data directory writable. If moco-init fails with "Permission denied", uncomment the following settings.
      # securityContext:
      #   fsGroup: 10000
      #   fsGroupChangePolicy: "OnRootMismatch"  # available since k8s 1.20
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - mysql
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - test
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mysqld
          image: quay.io/cybozu/mysql:8.0.31
          resources:
            limits:
              memory: "6364Mi" # 6604
              cpu: "3620m" # 4020
  volumeClaimTemplates:
    # At least a PVC named "mysql-data" must be defined.
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 120Gi
  primaryServiceTemplate:
    metadata:
      annotations:
#        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: nlb-ip
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
#        service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    spec:
      type: LoadBalancer
#  mycnf: |
#    [mysqld]
#    max_connections=162
#    core_file
#    local_infile=off
